language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
branches:
- master
- tchin006/AWS_Atmega
- cgray009/functionality
- jhalvorson6687/unit_tests
env:
  global:
  - secure: cR83EFK7Giz8hMrj2pZgK/yFpe9cmLaJZxP2zwY5x65/uVT4tzsOzhsRTl/RJVkCE8BoUhsctlg0xtIBZ0Z/E/+qPiDB4eeNPRPgTkE8PC6A3jFEriG63YDio5t09YWh+QBVZuszYanAxeCcUwICVV2vnoZYUZVW7BJxTFHBaKBOMxLKgQfV7fjKB9GuVCPzcz8sKnRLal+7cYQ8PZzHhqRdZvlOstmvWRlQHnyBcvsOlGjqWc44oVGlAT7Usc7SDxgL7sHAVLFDua3U5XLHEuoXau9Wro3SKrK+F/wSDgml+S2NngSGjV+XGCds9mVjTUvN1Et3jGgXCkxa9jiYPDz2Cq30dNPPzp+suyqmIHKJ8+D9p6o+Qey20lWtWzPWvrQMMoYRAheB76FDAn8Q1zfSqoJWP7Y1fTyPODRjVTnFZXXBfyhOG1PswbTm6gblLvrdqkz1kC97sb41aQJFUzkAn5xYePvQm8wz+UZZFBseC9LmuDi9p0gpq+sMkvqpTa5STqTylJdZXaOE2TCGpx2cu1S+GYsNTbpQHET77Dg8p5SrM6Te1XkAM2WkcyunOs/i2XUQ72wRsAIz9zgstYBXEJrK6KQ39141CtfWd0H9A6owmBo8q+pkg69/Pgjj5lfiCnCGjmYlq+ECl31WJRFYK2kLHnV3RNGc5OTYvWg=
  - secure: ZkZNW1exF5OiKTnnCPOGNn2PzH/3vR61IN+f5ZxtQK/nY8B+Sw5ghrAPQEh8yGx80fYs0tx29EsNO36OS/VncjlOgl/+1cWpfju7GosjARSZVRiNNWoH4fr2vycFB0VVkMSuSpnuhOqTs7Fba/HOFcuLhKWVUxKUWIdYnVU3AJUWfAZd5RV+bBbLqfP5GDfdDk5tna5sr1xjqEOFipebxlychYWjJLeFU5EYzmZqjSopDJ/SlbSrMjhuv9g0eKIeqhdH+h4b061v8H7iSHaYzU/vdggrooqDNUoicBoc0vxIAiar+EuqC68g8LHMKTvGJf73DRtsIUDCYGNw0FLI+yFw84ZuYdg3k4lq8HnZxWxnsttMO3UF+Eueyt6CtmU9M6Ltkgdltx1TDkM9O4KPW8ueupbkVILlLpNvFyFjbgntIRsr/MfWWHDPJJtE2ycPvNCTnk5kHEVaNwjDc7nOrkW5NagSbY3F4jrfd8qxwJ0b723qkY9J1DgLs4lYw6nbur6AynXAkZ7X3G0H+l4DCads/G+H6sk/4jAYPVFlRAReqT5UcN9cArxT4IvyQDfXPxnpVeNhgsb6+7JKAYjL0lsPqvcGvKQO33g2pHBO5kigi8eehbSQNEKH4MYwSMwbXABIgh7YxlWYRCpldhfASri693qItDCFFLz8YZX5Yyk=
