language: c

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

#dependencies
install:
  - pip install -r requirements.txt
  
env:
  global:
    - secure: "B9TQRzWIFua7cBBQX23EOzXGBcBpSs4w6aF3zUyUmoNJ+IX45Vvj4ZxsONbjLmJ1iKFgiCuILiirwLI+LusgFFPTBZ89jZa4OYqHukqTrobZSNgWQH2yih8YUN72OiSrqwAZEGWxZ5kMA6N0M5iHvQat1AJaaniciqi/2qvsH/GYVYxD5H+Z7C4EqCxq4GNwl0a3us4BaY+vqeI72jnvm/Gjo6gKnUjHLCT7Zg9//enPhTtKeadBlsCpJoBmCJNqp9au0TE/2pa78OX3KlKsaYAQmarZaFoqAxcsQvDYiotjKgDuQRxxYHlMnMzN/fLBkqf90ooa8q6F5Bah/9JjE4rYOpQMjbS8WZujxJV/ldnf8ihlX3OKYRH8x3ICTLup4k9Osxdsdpf8LC6Niyo7fE9ylufn8x+jAjFcM+BcjcUQCdI48imTlFBn8cNOjy27M+2g77ms73jZqkI2GYY2ELqtyWvL/iBtgWKSnfv/5HSGcaXPQhHirAEzbi6fw1/+LufFRVQ2aBX7ShNqHazf6KORM+p3VC1YM20bgjmvc3GS4MCD6QOwERSRdQTVDfWT0MYzsPqWN8w+sfMVJuhp7hLhyAiNktraFO/Xz82ayDXDBplmz8VfSO7xBYFkv9RVzLaOMLjK/rrorFT1u0UNDLoDM8Xb/Csr5dQGVZX6a6U="
    - secure: "DPS/H+meg2jY6tQnUt5BE4G0OHRGTGQIxQXfCZlwGauBrUomktePVa6uZhKEzq1kUgIxO+J1kAegXIfW2JLfuLeHk8WPElyUsmwfdXI3DQPnsmKXlLyQS2STYjPXMCozf/bGE9CZZQZTEk3eI4BEgjsh8UPfRRNGcOKaa/n5sxpBty8DWYDilHwAlWOPLs/BANrr5hic/I6A8g00G3vo6zQqMfiaasG723WX33Lqe6Tkx1xwFiaK4cM8V17nol7FYlifcpxp5AzMm4WukdEhZ6jjhcDHp2jeso4NNzXFb3uyJ7pLtr5aOJkh6NxR6ROXV3XER5U4hv3tAtfPc2IYnslFN58WE0LGYotK2rvClQIqUkcosVgRsCJnwSE4MyXMXPf7X+OUEYuR8Or3wgi2H2VLmPI02res38/wuYW1fk/smCNDEEnRoevAES9jICShgCveLd2rNIoBIC5HFeTm/uKoKybAacQz1Vwpm3VQDR8iSNMJb8rRvz7WCJgo61IM/6bclwGx7Wf7/xrSEJg/RNZECFDW+VWjkwryHrLKHNgCGyMS0XfL+a1kgNfsTmtu1EVB0/2mdAvq5WIDkr6nR6HjwRGLZ2LnLGzN9alaJjLuHOsPTnNHGaIypq4becfM1rDnoMxj8T8ius5SpDK6ZM/cRhBjVuTDMqwsfIats2U="


#run tests
script:
  - pytest

branches:
  - master
  - tchin006/AWS_Atmega
  - cgray009/functionality
  - jhalvorson6687/unit_tests
